GET http://localhost:8080/api/tickets?searchText=need

###

PATCH http://localhost:8080/api/tickets/6059c1616d1dbe3d4c5ac91d/done

###

PATCH http://localhost:8080/api/tickets/6059c1616d1dbe3d4c5ac91d/undone